### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Tosko4** [ManuCart/Cryptocurrency-Portfolio#27]
Is there any way we can get a feature to track profit/loss on each coin? 

Let's say I made 4 purchases in 1 coin. I would like to check whether my coin is in profit or loss

**Comment by ManuCart** [comment]
I was allready thinking about this feature, and beginning to work on it
But it's to complex to implement, because you can buy a coin with BTC and after by same coin with ETH and sold the coin with BNB. 
Another thing is about withdrawal between providers.
Let say you buy on binance and sold on bittrex with some transaction fee.
If you want this tools I advise you to use cointracking.info or other tools like this
It's not the perfect tools but it can help

**Comment by Tosko4** [comment]
@ManuCart I actually prefer the Excel as I am sure only I then own the API codes :)
I understand its complicated, no rush! 🆗
